# Generated by Django 4.2.7 on 2023-11-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0003_post_updated_at_alter_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='count',
        ),
    ]
